import { Download, FileJson, FileText } from 'lucide-react';
import { AnalysisResult } from '../types/analysis';
import toast from 'react-hot-toast';

interface ExportReportProps {
    result: AnalysisResult;
}

export function ExportReport({ result }: ExportReportProps) {
    const generateTextReport = (): string => {
        const { threat, file, analysis, steganography } = result;

        return `
═══════════════════════════════════════════════════════
          SENTINEL AI - SECURITY ANALYSIS REPORT
═══════════════════════════════════════════════════════

FILE INFORMATION
────────────────────────────────────────────────────────
Name:           ${file.filename}
Size:           ${(file.size / 1024).toFixed(2)} KB
Type:           ${file.type || 'Unknown'}
SHA-256:        ${analysis.metadata?.hash || 'N/A'}
Analyzed:       ${new Date().toLocaleString()}

THREAT ASSESSMENT
────────────────────────────────────────────────────────
Threat Level:   ${threat.level}
Confidence:     ${threat.confidence}%

SUMMARY
────────────────────────────────────────────────────────
${threat.summary}

${threat.reasoning ? `
DETAILED REASONING
────────────────────────────────────────────────────────
${threat.reasoning}
` : ''}

${threat.predictedAttackVector ? `
PREDICTED ATTACK VECTOR
────────────────────────────────────────────────────────
${threat.predictedAttackVector}
` : ''}

${threat.indicators && threat.indicators.length > 0 ? `
THREAT INDICATORS
────────────────────────────────────────────────────────
${threat.indicators.map((ind: string, i: number) => `${i + 1}. ${ind}`).join('\n')}
` : ''}

${analysis.entropy ? `
ENTROPY ANALYSIS
────────────────────────────────────────────────────────
Measured:       ${analysis.entropy}
` : ''}

${steganography?.detected ? `
STEGANOGRAPHY DETECTED
────────────────────────────────────────────────────────
Confidence:     ${steganography.confidence}%
Analysis:       ${steganography.analysis}
${steganography.techniques && steganography.techniques.length > 0 ? `Techniques:     ${steganography.techniques.map(t => t.name).join(', ')}` : ''}
` : ''}

RECOMMENDATIONS
────────────────────────────────────────────────────────
${threat.recommendation || 'No specific recommendations'}

═══════════════════════════════════════════════════════
          Generated by Sentinel AI - Powered by Gemini
═══════════════════════════════════════════════════════
    `.trim();
    };

    const generateJSONReport = (): string => {
        return JSON.stringify(result, null, 2);
    };

    const downloadFile = (content: string, filename: string, mimeType: string) => {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    const handleExportText = () => {
        const content = generateTextReport();
        const filename = `sentinel_report_${result.file.filename}_${Date.now()}.txt`;
        downloadFile(content, filename, 'text/plain');
        toast.success('Report exported as TXT');
    };

    const handleExportJSON = () => {
        const content = generateJSONReport();
        const filename = `sentinel_report_${result.file.filename}_${Date.now()}.json`;
        downloadFile(content, filename, 'application/json');
        toast.success('Report exported as JSON');
    };

    const handleCopyToClipboard = async () => {
        try {
            await navigator.clipboard.writeText(generateTextReport());
            toast.success('Report copied to clipboard');
        } catch (err) {
            toast.error('Failed to copy to clipboard');
        }
    };

    return (
        <div className="flex gap-2 flex-wrap">
            <button
                onClick={handleExportText}
                className="flex items-center gap-2 px-4 py-2 bg-sentinel-card border border-sentinel-border hover:bg-sentinel-border text-gray-300 rounded-lg transition"
            >
                <FileText className="w-4 h-4" />
                Export TXT
            </button>

            <button
                onClick={handleExportJSON}
                className="flex items-center gap-2 px-4 py-2 bg-sentinel-card border border-sentinel-border hover:bg-sentinel-border text-gray-300 rounded-lg transition"
            >
                <FileJson className="w-4 h-4" />
                Export JSON
            </button>

            <button
                onClick={handleCopyToClipboard}
                className="flex items-center gap-2 px-4 py-2 bg-sentinel-card border border-sentinel-border hover:bg-sentinel-border text-gray-300 rounded-lg transition"
            >
                <Download className="w-4 h-4" />
                Copy Report
            </button>
        </div>
    );
}
